site_name: TD Airflow
theme:
  name: material
  features:
    - content.tabs
    - content.code.copy
    - toc.integrate
    - navigation.sections
    - toc.follow
    - navigation.indexes
    - content.presentation

extra_javascript:
  - javascripts/custom.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
        - locale: fr
          name: Français
          default: true
          build: true
  - slides:
      template: "layouts/slide_template1.html"  # Custom slide template

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 1

nav:
  - Overview: index.md
  - 0 - Installation: Installation.md
  - 1 - Hello World: Hello-world.md
  - 2 - Création d'un DAG : DAG_simple.md
  - 3 - Utilisation de FileSensor : FileSensor.md