site_name: TD Airflow
theme:
  name: material
  features:
    - content.tabs
    - content.code.copy
    - toc.integrate
    - navigation.sections
    - toc.follow
    - navigation.indexes

extra_javascript:
  - javascripts/custom.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 1

nav:
  - Overview: index.md
  - 0 - Installation: Installation.md
  - 1 - Hello World: Hello-world.md
  - 2 - Création d'un DAG simple: DAG_simple.md